services:
  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      DATABASE_NAME: ${DATABASE_NAME:-postgres}
      DATABASE_USER: ${DATABASE_USER:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-postgres}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    environment:
      NODE_ENV: production
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: db
    command: ["make", "test"]
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: