name: Build & Push to Docker Hub

on:
  push:
    branches:
      - main

env:
  CI: true
  APP_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/devops-for-programmers-project-74
  DATABASE_NAME: postgres
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: postgres

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run tests (Docker Compose)
        run: make ci
